import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/providers/core_providers.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_theme.dart';
import 'app_decorations.dart';

final aiInsightsProvider = FutureProvider<List<dynamic>>((ref) async {
  return ref.read(apiServiceProvider).getAiInsights(period: 'daily');
});

class AiCoachTips extends ConsumerStatefulWidget {
  const AiCoachTips({super.key});

  @override
  ConsumerState<AiCoachTips> createState() => _AiCoachTipsState();
}

class _AiCoachTipsState extends ConsumerState<AiCoachTips> {
  bool _autoGenerated = false;

  @override
  Widget build(BuildContext context) {
    final insightsAsync = ref.watch(aiInsightsProvider);
    final colors = context.appColors;

    insightsAsync.whenData((insights) {
      if (!_autoGenerated && insights.isEmpty) {
        _autoGenerated = true;
        Future.microtask(() async {
          await ref.read(apiServiceProvider).generateDailyInsights();
          ref.invalidate(aiInsightsProvider);
        });
      }
    });

    return Container(
      decoration: AppDecorations.card(context),
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              gradient: LinearGradient(colors: [Theme.of(context).colorScheme.primary.withValues(alpha: 0.06), colors.card]),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: AppDecorations.iconBadge(Theme.of(context).colorScheme.primary),
                  child: Icon(Icons.lightbulb_outline_rounded, size: 18, color: Theme.of(context).colorScheme.primary),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    'Money notes',
                    style: TextStyle(
                      fontWeight: FontWeight.w700,
                      fontSize: 16,
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.refresh_rounded, size: 20),
                  onPressed: () async {
                    await ref.read(apiServiceProvider).generateDailyInsights();
                    ref.invalidate(aiInsightsProvider);
                  },
                ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: insightsAsync.when(
              loading: () => const Center(child: Padding(padding: EdgeInsets.all(16), child: CircularProgressIndicator())),
              error: (_, __) => Text('Could not load notes', style: TextStyle(color: colors.mutedForeground)),
              data: (insights) {
                final tips = insights.take(3).toList();
                if (tips.isEmpty) {
                  return Text(
                    'Add your salary and a few expenses. Notes will show up here.',
                    style: TextStyle(color: colors.mutedForeground, fontSize: 14),
                  );
                }
                return Column(
                  children: tips.map((t) {
                    final tip = t as Map<String, dynamic>;
                    final severity = tip['severity']?.toString() ?? 'info';
                    final color = _severityColor(severity);
                    return Container(
                      margin: const EdgeInsets.only(bottom: 10),
                      padding: const EdgeInsets.all(14),
                      decoration: BoxDecoration(
                        color: color.withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(12),
                        border: Border(left: BorderSide(color: color, width: 4)),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            tip['title']?.toString() ?? '',
                            style: TextStyle(
                              fontWeight: FontWeight.w700,
                              color: Theme.of(context).colorScheme.onSurface,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(tip['content']?.toString() ?? '', style: TextStyle(color: colors.mutedForeground, height: 1.4)),
                        ],
                      ),
                    );
                  }).toList(),
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  Color _severityColor(String severity) {
    switch (severity) {
      case 'success': return AppTheme.success;
      case 'warning': return AppTheme.warning;
      case 'critical': return AppTheme.danger;
      default: return AppTheme.primary;
    }
  }
}
