'use client';

import { useEffect, useRef } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Lightbulb, RefreshCw } from 'lucide-react';
import { aiInsightsApi } from '@/lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/lib/utils';

interface AiInsight {
  id: string;
  title: string;
  content: string;
  severity: string;
  category?: string | null;
  isRead: boolean;
  createdAt: string;
}

const SEVERITY_STYLES: Record<string, string> = {
  success: 'border-l-emerald-500 bg-emerald-50/80 dark:bg-emerald-950/30',
  warning: 'border-l-amber-500 bg-amber-50/80 dark:bg-amber-950/30',
  critical: 'border-l-rose-500 bg-rose-50/80 dark:bg-rose-950/30',
  info: 'border-l-primary bg-muted/40',
};

export function AiCoachTips() {
  const queryClient = useQueryClient();

  const { data: insights, isLoading } = useQuery({
    queryKey: ['ai-insights', 'daily'],
    queryFn: () => aiInsightsApi.list({ period: 'daily' }) as Promise<AiInsight[]>,
  });

  const generate = useMutation({
    mutationFn: () => aiInsightsApi.generateDaily(),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['ai-insights'] }),
  });

  const autoGenerated = useRef(false);

  useEffect(() => {
    if (
      !autoGenerated.current &&
      !isLoading &&
      (insights ?? []).length === 0 &&
      !generate.isPending
    ) {
      autoGenerated.current = true;
      generate.mutate();
    }
  }, [isLoading, insights, generate]);

  const tips = (insights ?? []).filter((i) => !i.isRead).slice(0, 3);
  const displayTips = tips.length > 0 ? tips : (insights ?? []).slice(0, 3);

  return (
    <Card className="overflow-hidden">
      <CardHeader className="flex flex-row items-center justify-between gap-2 border-b bg-gradient-to-r from-primary/5 to-transparent pb-4">
        <CardTitle className="flex items-center gap-2 text-base">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10">
            <Lightbulb className="h-4 w-4 text-primary" />
          </span>
          Money notes
        </CardTitle>
        <Button
          variant="ghost"
          size="sm"
          className="h-8 gap-1.5 rounded-lg text-xs"
          onClick={() => generate.mutate()}
          disabled={generate.isPending}
        >
          <RefreshCw className={cn('h-3.5 w-3.5', generate.isPending && 'animate-spin')} />
          Refresh
        </Button>
      </CardHeader>
      <CardContent className="space-y-2.5 pt-4">
        {isLoading || generate.isPending ? (
          <div className="space-y-2.5">
            {Array.from({ length: 2 }).map((_, i) => (
              <Skeleton key={i} className="h-16 rounded-xl" />
            ))}
          </div>
        ) : displayTips.length > 0 ? (
          displayTips.map((tip) => (
            <div
              key={tip.id}
              className={cn(
                'rounded-xl border-l-4 p-4 text-sm shadow-sm',
                SEVERITY_STYLES[tip.severity] ?? SEVERITY_STYLES.info,
              )}
            >
              <p className="font-semibold">{tip.title}</p>
              <p className="mt-1 leading-relaxed text-muted-foreground">{tip.content}</p>
            </div>
          ))
        ) : (
          <p className="py-4 text-center text-sm text-muted-foreground">
            Add your salary and a few expenses. Notes will show up here.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
